"""Add knowledge chunk deduplication unique constraint

Revision ID: 68a848528fe7
Revises: cf4e5605471b
Create Date: 2026-07-09 11:00:00.115564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a848528fe7'
down_revision: Union[str, Sequence[str], None] = 'cf4e5605471b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunks_user_topic_hash', 'knowledge_chunks', ['user_id', 'knowledge_topic_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunks_user_topic_hash', 'knowledge_chunks', type_='unique')
    # ### end Alembic commands ###
