"""Initial Schema

Revision ID: cf4e5605471b
Revises: 
Create Date: 2026-07-09 10:52:18.714752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4e5605471b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_topics',
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic_summary', sa.Text(), nullable=False),
    sa.Column('state_summary', sa.Text(), nullable=False),
    sa.Column('entities_json', sa.Text(), nullable=False),
    sa.Column('last_hop_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')"),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index('idx_topics_last_hop', 'conversation_topics', ['user_id', 'last_hop_id'], unique=False)
    op.create_index('idx_topics_user_status', 'conversation_topics', ['user_id', 'status'], unique=False)
    op.create_table('indexing_outbox',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("entity_type IN ('conversation_hop', 'knowledge_chunk')"),
    sa.CheckConstraint("operation IN ('upsert', 'delete')"),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')"),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('knowledge_topics',
    sa.Column('knowledge_topic_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entities_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_topic_id')
    )
    op.create_table('reminders',
    sa.Column('reminder_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_topic_id', sa.String(), nullable=True),
    sa.Column('source_hop_id', sa.String(), nullable=True),
    sa.Column('reminder_time', sa.String(), nullable=False),
    sa.Column('raw_reminder', sa.Text(), nullable=False),
    sa.Column('reminder_summary', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('supporting_question', sa.Text(), nullable=True),
    sa.Column('supporting_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'notified', 'dismissed', 'completed')"),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_index('idx_reminders_user_created', 'reminders', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_reminders_user_status_time', 'reminders', ['user_id', 'status', 'reminder_time'], unique=False)
    op.create_index('idx_reminders_user_updated', 'reminders', ['user_id', 'updated_at'], unique=False)
    op.create_table('conversation_hops',
    sa.Column('hop_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('raw_user_query', sa.Text(), nullable=False),
    sa.Column('rewritten_user_query', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('response_type', sa.String(), nullable=False),
    sa.Column('supporting_questions_json', sa.Text(), nullable=False),
    sa.Column('previous_hop_id', sa.String(), nullable=True),
    sa.Column('parent_hop_id', sa.String(), nullable=True),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('entities_json', sa.Text(), nullable=False),
    sa.Column('outbox_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("intent IN ('command', 'search', 'chat')"),
    sa.CheckConstraint("response_type IN ('text', 'rich_card', 'action')"),
    sa.ForeignKeyConstraint(['topic_id'], ['conversation_topics.topic_id'], ),
    sa.PrimaryKeyConstraint('hop_id')
    )
    op.create_index('idx_hops_topic_parent', 'conversation_hops', ['user_id', 'topic_id', 'parent_hop_id'], unique=False)
    op.create_index('idx_hops_topic_prev', 'conversation_hops', ['user_id', 'topic_id', 'previous_hop_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('knowledge_topic_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('is_deleted IN (0, 1)'),
    sa.ForeignKeyConstraint(['knowledge_topic_id'], ['knowledge_topics.knowledge_topic_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_chunks_user_topic_deleted', 'knowledge_chunks', ['user_id', 'knowledge_topic_id', 'is_deleted'], unique=False)
    op.create_table('reminder_notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('reminder_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ui_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('read_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.CheckConstraint("ui_status IN ('unread', 'read', 'deleted')"),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.reminder_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_notifications')
    op.drop_index('idx_chunks_user_topic_deleted', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('idx_hops_topic_prev', table_name='conversation_hops')
    op.drop_index('idx_hops_topic_parent', table_name='conversation_hops')
    op.drop_table('conversation_hops')
    op.drop_index('idx_reminders_user_updated', table_name='reminders')
    op.drop_index('idx_reminders_user_status_time', table_name='reminders')
    op.drop_index('idx_reminders_user_created', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('knowledge_topics')
    op.drop_table('indexing_outbox')
    op.drop_index('idx_topics_user_status', table_name='conversation_topics')
    op.drop_index('idx_topics_last_hop', table_name='conversation_topics')
    op.drop_table('conversation_topics')
    # ### end Alembic commands ###
